# Generated by Django 5.2 on 2025-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSIC',
            fields=[
                ('numero_sic', models.AutoField(primary_key=True, serialize=False)),
                ('es_muestra', models.BooleanField(default=False)),
                ('pertenece', models.CharField(default='Sección desconocida', max_length=255)),
                ('fecha_sic', models.DateField(auto_now_add=True)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('otro_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('especificacion_tecnica', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
    ]
