# Generated by Django 5.2 on 2025-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic_autorizaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsic',
            name='aprobado_por',
        ),
        migrations.AddField(
            model_name='solicitudsic',
            name='editada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudsic',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudsic',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
