# Generated by Django 5.2 on 2025-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic_autorizaciones', '0003_remove_solicitudsic_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsic',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Autorizado', 'Autorizado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
